### ISSUE TITLE
Different fingerprints for same document

### ISSUE THREAD

**Issue by srachuri** [themadcreator/rabinfingerprint#3]
I m trying to generate fingerprint for a string. Below is the code snippet

		String s = "quick brown";
		Polynomial polynomial = Polynomial.createIrreducible(53);
		RabinFingerprintLong rabin = new RabinFingerprintLong(polynomial);
		rabin.pushBytes(s.getBytes());
		System.out.println(rabin.getFingerprintLong());
		System.out.println(Long.toString(rabin.getFingerprintLong(), 16));

I am always seeing new values for the same string that i m trying to finger print.
I was planning to use the fingerprint for detecting duplicate documents. Not sure if the code is working as expected or i am missing any thing here?

**Comment by projectvalis** [comment]
did you use the same key in both instances?

**Comment by themadcreator** [comment]
In line 2 of this code block you generate a NEW irreducible polynomial every time this runs. To avoid this, you need to use the same polynomial each time.

Try printing out the hex digits of the polynomial and then construct the polynomial with that string.
