### ISSUE TITLE
problem with limit method

### ISSUE THREAD

**Issue by manishprabhu812** [themadcreator/rabinfingerprint#7]
for (Long key : Iterables.limit(keys, fingersPerHand))
it is showing an error
The method limit is undefined for the type Iterables can you suggest any solution?

**Comment by themadcreator** [comment]
What JVM version are you running? Also, what file is this in?

**Comment by manishprabhu812** [comment]
Microsoft Windows XP [Version 5.1.2600]
(C) Copyright 1985-2001 Microsoft Corp.

C:\Documents and Settings\Manish>java -version
java version "1.7.0_72"
Java(TM) SE Runtime Environment (build 1.7.0_72-b14)
Java HotSpot(TM) Client VM (build 24.72-b04, mixed mode, sharing)

this error is present in Handprint.java

**Comment by manishprabhu812** [comment]
please suggest me the solution

**Comment by themadcreator** [comment]
It seems like the main cause is an api change in the google guava lib. Try
downgrading that library to an earlier version

bd

**Comment by manishprabhu812** [comment]
now everything is fine
just tell me how to provide input to this program?

**Comment by manishprabhu812** [comment]
where is file.test?
what are its contents?

**Comment by themadcreator** [comment]
I'm glad to hear that fixed it.

"file.test" is just an example file name, replace it with the file name of whatever file you want to fingerprint.
